root = "."
testdata_dir = "testdata"
tmp_dir = ".tmp"

[build]
args_bin = []
bin = "./.tmp/main"
# TailwindCSS v4 experimentation... doh!
# cmd = "npx @tailwindcss/cli -i assets/css/input.css -o assets/css/styles.css && templ generate && go build -o ./.tmp/main ."
cmd = "npx tailwindcss -i assets/css/input.css -o assets/css/styles.css --minify && templ generate && go build -o ./.tmp/main ."
delay = 1000
exclude_dir = ["assets", ".tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go", "_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "templ"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true

[proxy]
enabled = true
proxy_port = 3001
app_port = 3000