run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags: []
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/alexander-bruun/magi
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
  misspell:
    locale: US
  lll:
    line-length: 120

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: utils/string_utils\.go
      linters:
        - typecheck
    - path: indexer/indexer\.go
      linters:
        - typecheck
  exclude-use-default: false
  exclude:
    - "G404" # Use of weak random number generator
    - "G501" # Import blacklist: crypto/md5
    - "G502" # Import blacklist: crypto/des
    - "G505" # Import blacklist: crypto/sha1