// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/alexander-bruun/magi/models"
)

func ExternalAccountsPage(accounts []models.UserExternalAccount) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = PageTitle("External Accounts").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Breadcrumb([]BreadcrumbItem{
			{Label: "Home", Href: "/"},
			{Label: "Account", Href: "/account"},
			{Label: "External Accounts", Href: "/account/external"},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h2 class=\"uk-heading-line uk-h2 uk-card-title uk-text-center\"><span>External Accounts</span></h2><p class=\"uk-text-center uk-text-muted mb-6\">Connect your accounts to sync reading progress with external services.</p><div class=\"grid grid-cols-1 lg:grid-cols-2 gap-6\"><div class=\"uk-card uk-card-default uk-card-body\"><h3 class=\"uk-h4 mb-4\">MyAnimeList</h3>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		malAccount := (models.UserExternalAccount{})
		for _, account := range accounts {
			if account.ServiceName == "mal" {
				malAccount = account
			}
		}
		if malAccount.ServiceName == "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p class=\"mb-4\">Connect your MyAnimeList account to sync reading progress.</p><form hx-post=\"/account/external/mal/connect\" hx-target=\"#content\" hx-swap=\"innerHTML\" hx-ext=\"form-json\"><div class=\"uk-margin\"><label class=\"uk-form-label\" for=\"client_id\">Client ID <button type=\"button\" uk-tooltip=\"title: 1. Go to MAL API Config<br>2. Create a new application<br>3. Copy the Client ID; pos: top-left\" class=\"uk-icon-button uk-icon-button-small\"><uk-icon icon=\"Question\"></uk-icon></button></label><div class=\"uk-form-controls\"><input class=\"uk-input\" id=\"client_id\" name=\"client_id\" type=\"text\" required></div></div><div class=\"uk-margin\"><label class=\"uk-form-label\" for=\"client_secret\">Client Secret <button type=\"button\" uk-tooltip=\"title: 1. Go to MAL API Config<br>2. Create a new application<br>3. Copy the Client Secret; pos: top-left\" class=\"uk-icon-button uk-icon-button-small\"><uk-icon icon=\"Question\"></uk-icon></button></label><div class=\"uk-form-controls\"><input class=\"uk-input\" id=\"client_secret\" name=\"client_secret\" type=\"password\" required></div></div><button class=\"uk-btn uk-btn-primary\" type=\"submit\">Save Credentials</button></form><div class=\"uk-alert uk-alert-primary uk-margin-small\"><p><strong>Important:</strong> When creating your MAL application, set the redirect URI to:</p><code>http://localhost:3000/external/callback/mal</code></div><p><small>Get your Client ID and Secret from <a href=\"https://myanimelist.net/apiconfig\" target=\"_blank\">MAL API Config</a></small></p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if malAccount.AccessToken == "" || len(malAccount.AccessToken) < 30 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<p class=\"mb-4\">Your MyAnimeList credentials are saved.</p><a href=\"/account/external/mal/authorize\" class=\"uk-btn uk-btn-secondary mr-2\">Authorize with MyAnimeList</a><form hx-post=\"/account/external/mal/disconnect\" hx-target=\"#content\" hx-swap=\"innerHTML\" class=\"form-inline\"><button class=\"uk-btn uk-btn-destructive\" type=\"submit\">Disconnect</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<p class=\"mb-4\">Your MyAnimeList account is authorized.</p><button class=\"uk-btn uk-btn-secondary mr-2\" disabled>Authorized</button><form hx-post=\"/account/external/mal/disconnect\" hx-target=\"#content\" hx-swap=\"innerHTML\" class=\"form-inline\"><button class=\"uk-btn uk-btn-destructive\" type=\"submit\">Disconnect</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div class=\"uk-card uk-card-default uk-card-body\"><h3 class=\"uk-h4 mb-4\">AniList</h3>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		anilistAccount := (models.UserExternalAccount{})
		for _, account := range accounts {
			if account.ServiceName == "anilist" {
				anilistAccount = account
			}
		}
		if anilistAccount.ServiceName == "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<p class=\"mb-4\">Connect your AniList account to sync reading progress.</p><form hx-post=\"/account/external/anilist/connect\" hx-target=\"#content\" hx-swap=\"innerHTML\" hx-ext=\"form-json\"><div class=\"uk-margin\"><label class=\"uk-form-label\" for=\"client_id\">Client ID <button type=\"button\" uk-tooltip=\"title: 1. Go to AniList Developer Settings<br>2. Create a new application<br>3. Copy the Client ID; pos: top-left\" class=\"uk-icon-button uk-icon-button-small\"><uk-icon icon=\"Question\"></uk-icon></button></label><div class=\"uk-form-controls\"><input class=\"uk-input\" id=\"client_id\" name=\"client_id\" type=\"text\" required></div></div><div class=\"uk-margin\"><label class=\"uk-form-label\" for=\"client_secret\">Client Secret <button type=\"button\" uk-tooltip=\"title: 1. Go to AniList Developer Settings<br>2. Create a new application<br>3. Copy the Client Secret; pos: top-left\" class=\"uk-icon-button uk-icon-button-small\"><uk-icon icon=\"Question\"></uk-icon></button></label><div class=\"uk-form-controls\"><input class=\"uk-input\" id=\"client_secret\" name=\"client_secret\" type=\"password\" required></div></div><button class=\"uk-btn uk-btn-primary\" type=\"submit\">Save Credentials</button></form><div class=\"uk-alert uk-alert-primary uk-margin-small\"><p><strong>Important:</strong> When creating your AniList application, set the redirect URI to:</p><code>http://localhost:3000/external/callback/anilist</code></div><p><small>Get your Client ID and Secret from <a href=\"https://anilist.co/settings/developer\" target=\"_blank\">AniList Developer Settings</a></small></p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if anilistAccount.AccessToken == "" || len(anilistAccount.AccessToken) < 30 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<p class=\"mb-4\">Your AniList credentials are saved.</p><a href=\"/account/external/anilist/authorize\" class=\"uk-btn uk-btn-secondary mr-2\">Authorize with AniList</a><form hx-post=\"/account/external/anilist/disconnect\" hx-target=\"#content\" hx-swap=\"innerHTML\" class=\"form-inline\"><button class=\"uk-btn uk-btn-destructive\" type=\"submit\">Disconnect</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<p class=\"mb-4\">Your AniList account is authorized.</p><button class=\"uk-btn uk-btn-secondary mr-2\" disabled>Authorized</button><form hx-post=\"/account/external/anilist/disconnect\" hx-target=\"#content\" hx-swap=\"innerHTML\" class=\"form-inline\"><button class=\"uk-btn uk-btn-destructive\" type=\"submit\">Disconnect</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
